import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.findLab': 'Trouver un Laboratoire',
    'nav.findClient': 'Trouver un Client',
    'nav.results': 'Mes Résultats',
    'nav.login': 'Se Connecter',
    'nav.PADRequests': 'Demandes PAD',
    'nav.logout': 'Se Déconnecter',

    // Hero Section
    'hero.title': 'Laboratoire d\'Analyses Médicales',
    'hero.subtitle': 'Trouvez le laboratoire le plus proche de chez vous pour vos analyses sanguines et urinaires.',
    'hero.findLab': 'Trouver un Laboratoire',
    'hero.login': 'Se Connecter',

    // Features
    'features.title': 'Pourquoi Choisir Notre Plateforme ?',
    'features.subtitle': 'Découvrez les avantages de notre réseau de laboratoires médicaux et profitez d\'un service de qualité adapté à vos besoins.',
    'features.analyses.title': 'Analyses Complètes',
    'features.analyses.desc': 'Tests sanguins, urinaires et biochimiques avec des équipements de pointe et des résultats fiables.',
    'features.results.title': 'Résultats Rapides',
    'features.results.desc': 'Accès en ligne à vos résultats de tests le plus rapidement possible, 24h/7j.',
    'features.home.title': 'Collecte à Domicile',
    'features.home.desc': 'Service de collecte à domicile pour votre confort et votre sécurité.',
    'features.security.title': 'Sécurité et Confidentialité',
    'features.security.desc': 'Protection complète de vos données médicales avec chiffrement et conformité RGPD.',
    'features.team.title': 'Équipe Professionnelle',
    'features.team.desc': 'Biologistes et techniciens qualifiés pour une analyse de haute qualité.',
    'features.tracking.title': 'Suivi Personnalisé',
    'features.tracking.desc': 'Historique complet de vos analyses et conseils personnalisés de nos experts.',

    // Find Laboratory
    'findLab.title': 'Trouvez un Laboratoire Près de Chez Vous',
    'findLab.subtitle': 'Localisez rapidement les laboratoires d\'analyses médicales dans votre région et prenez rendez-vous en quelques clics.',
    'findLab.seoTitle': 'Trouver un Laboratoire - Analyses Médicales',
    'findLab.seoDescription': 'Trouvez le laboratoire d\'analyses médicales le plus proche de chez vous. Localisation, horaires et services disponibles.',
    'findLab.keyword1': 'trouver laboratoire',
    'findLab.keyword2': 'laboratoire proche',
    'findLab.keyword3': 'analyses médicales',
    'findLab.keyword4': 'localisation laboratoire',
    'findLab.placeholder': 'Entrez votre adresse ou code postal',
    'findLab.myLocation': 'Ma position',
    'findLab.search': 'Rechercher',
    'findLab.call': 'Appeler',
    'findLab.homeCollection': 'Collecte à domicile',
    'findLab.services': 'Services:',
    'findLab.notFound': 'Vous ne trouvez pas de laboratoire dans votre région ?',
    'findLab.contact': 'Contactez-nous pour plus d\'informations',
    'findLab.goLocation': 'Aller au lieu',
    'findLab.searching': 'Recherche en cours...',
    'findLab.loading': 'Chargement des laboratoires...',
    'findLab.found': 'Laboratoires trouvés ({count})',
    'findLab.defaultName': 'Laboratoire',
    'findLab.phoneNotAvailable': 'Téléphone non disponible',
    'findLab.mapCentered': 'Carte recentrée',
    'findLab.mapCenteredDesc': 'Carte centrée sur {labName}',
    'findLab.noResults': 'Aucun laboratoire trouvé dans cette zone.',

    // Map page strings
    'map.locationRequired': 'Localisation requise',
    'map.needLocation': 'Nous avons besoin de votre position pour afficher les laboratoires proches',
    'map.nearbyLabs': 'Laboratoires Proches',
    'map.scrollHint': 'Faites défiler pour voir tous les laboratoires',
    'map.openDays': 'Jours ouverts',
    'map.requestPAD': 'Demander PAD',
    'map.locating': 'Localisation...',
    'map.refreshPosition': 'Actualiser Position',
    'map.goToMyPlace': 'Ma position',
    'map.positionUnknown': 'Position inconnue',
    'map.enableLocation': 'Activez votre localisation d\'abord.',
    'map.alreadySent': 'Déjà envoyé',
    'map.alreadySentDesc': 'Vous avez déjà envoyé une demande. Veuillez attendre la réponse.',
    'map.accuracyApproximate': 'Position approximative',
    'map.accuracyVeryPrecise': 'Position très précise',
    'map.accuracyPrecise': 'Position précise',
    'map.accuracyGood': 'Position bonne',
    'map.accuracyIP': 'Position basée sur IP',
    'map.interactiveMap': 'Carte Interactive',
    'map.yourPosition': 'Votre Position',
    'map.accuracy': 'Précision: ±{meters}m',
    'map.loadingLabs': 'Chargement des laboratoires...',
    'map.noLabsInDB': 'Aucun laboratoire dans la base de données',
    'map.noLabsAvailable': 'Aucun laboratoire vérifié n\'est disponible pour le moment',
    'map.call': 'Appeler',
    'map.directions': 'Itinéraire',
    'map.goToLocation': 'Aller à',
    'map.laboratories': 'laboratoires',

    // PAD strings
    'PAD.loginRequired': 'Vous devez être connecté pour envoyer une demande PAD.',
    'PAD.sendError': 'Impossible d\'envoyer la demande PAD.',
    'PAD.sendSuccess': 'Demande envoyée',
    'PAD.sendSuccessDesc': 'Demande PAD envoyée à {labName}',
    'PAD.defaultMessage': 'Demande de PAD envoyée par le client',
    'PAD.newRequest.title': 'Nouvelle demande PAD',
    'PAD.newRequest.message': 'a envoyé une demande PAD.',
    'PAD.sentTitle': 'Demande envoyée',
    'PAD.sentDesc': 'Demande PAD envoyée à',
    'PAD.acceptedTitle': 'PAD acceptée',
    'PAD.acceptedMessage': 'Le laboratoire a accepté votre demande. Restez joignable, ils peuvent vous appeler.',

    // Common
    'common.error': 'Erreur',
    'common.aClient': 'Un client',
    'common.refresh': 'Actualiser',

    // Hero (authenticated variants)
    'hero.auth.clientTitle': 'Trouvez votre laboratoire',
    'hero.auth.labTitle': 'Gérez vos analyses',
    'hero.auth.clientSubtitle': 'Découvrez les laboratoires proches et prenez rendez-vous facilement.',
    'hero.auth.labSubtitle': 'Accédez à vos demandes d\'analyses et gérez vos résultats.',

    // Authentication
    'auth.login': 'Se Connecter',
    'auth.signup': 'S\'Inscrire',
    'auth.loginTitle': 'Connexion',
    'auth.signupTitle': 'Créer un Compte',
    'auth.loginSubtitle': 'Accédez à votre espace personnel',
    'auth.signupSubtitle': 'Rejoignez notre plateforme de laboratoires',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.client': 'Client',
    'auth.laboratory': 'Laboratoire',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.phone': 'Téléphone',
    'auth.birthDate': 'Date de naissance',
    'auth.labName': 'Nom du laboratoire',
    'auth.professionalEmail': 'Email professionnel',
    'auth.siret': 'Numéro SIRET',
    'auth.address': 'Adresse',
    'auth.terms': 'J\'accepte les conditions d\'utilisation',
    'auth.professionalTerms': 'J\'accepte les conditions professionnelles',
    'auth.createAccount': 'Créer un compte',

    // Services
    'services.bloodTests': 'Tests Sanguins',
    'services.bloodTests.desc': 'Tests sanguins et biochimiques complets',
    'services.urineTests': 'Tests Urinaires',
    'services.urineTests.desc': 'Examens urinaires complets',
    'services.homeCollection': 'Collecte à Domicile',
    'services.homeCollection.desc': 'Service de collecte à votre domicile',
    'services.rapidResults': 'Résultats Rapides',
    'services.rapidResults.desc': 'Accès en ligne à vos résultats',

    // Results
    'results.title': 'Mes Résultats',
    'results.download': 'Télécharger',
    'results.status.completed': 'Terminé',
    'results.status.pending': 'En attente',
    'results.status.reviewed': 'Examiné',
    'results.labHistory': 'Historique des résultats envoyés aux clients',
    'results.clientHistory': 'Historique de vos résultats de tests médicaux',
    'results.searchPlaceholder': 'Rechercher par titre, description ou nom...',
    'results.results': 'Résultats',
    'results.loading': 'Chargement...',
    'results.found': 'résultat(s) trouvé(s)',
    'results.loadingResults': 'Chargement des résultats',
    'results.loadError': 'Impossible de charger les résultats.',
    'results.downloadStarted': 'Téléchargement commencé',
    'results.downloading': 'Téléchargement',
    'results.downloadErrorTitle': 'Erreur de téléchargement',
    'results.downloadErrorDesc': 'Impossible de télécharger le fichier.',
    'results.newAvailableTitle': 'Nouveau résultat disponible',
    'results.newAvailableMessage': 'Le laboratoire a envoyé un résultat: "{filename}".',

    // Laboratory dashboard
    'lab.header': 'Tableau de Bord - Laboratoire',
    'lab.headerSubtitle': 'Gérez vos demandes, résultats et paramètres de laboratoire',
    'lab.findClient': 'Trouver un Client',
    'lab.PADRequests': 'Demandes PAD',
    'lab.searchClients': 'Rechercher des Clients',
    'lab.searchClientsDesc': 'Trouvez des clients et envoyez-leur des demandes PAD',
    'lab.searchPlaceholder': 'Rechercher par nom, email ou téléphone...',
    'lab.sendResult': 'Envoyer Résultat',
    'lab.noClientFor': 'Aucun client trouvé',
    'lab.noClientsYet': 'Aucun client inscrit pour le moment',
    'lab.noClientsHint': 'Les clients apparaîtront ici une fois qu\'ils se seront inscrits sur la plateforme',
    'lab.receivedPAD': 'Demandes PAD Reçues',
    'lab.receivedPADDesc': 'Gérez les demandes PAD envoyées par les clients',
    'lab.status.pending': 'En attente',
    'lab.status.accepted': 'Acceptée',
    'lab.status.rejected': 'Refusée',
    'lab.viewExactLocation': 'Voir Localisation Exacte',
    'lab.accept': 'Accepter',
    'lab.reject': 'Refuser',

    // Laboratory Home Page
    'labHome.seoTitle': 'Espace Laboratoire - SihaaExpress',
    'labHome.seoDescription': 'Plateforme complète pour les laboratoires d\'analyses médicales. Connectez-vous avec les clients, gérez les demandes et optimisez votre flux de travail.',
    'labHome.keyword1': 'laboratoire',
    'labHome.keyword2': 'analyses médicales',
    'labHome.keyword3': 'PAD',
    'labHome.keyword4': 'résultats',
    'labHome.title': 'Espace Laboratoire',
    'labHome.heroDescription': 'Plateforme complète pour les laboratoires d\'analyses médicales. Connectez-vous avec les clients, gérez les demandes et optimisez votre flux de travail.',
    'labHome.ctaFindClients': 'Trouver des Clients',
    'labHome.ctaManageRequests': 'Gérer les Demandes',
    'labHome.features.title': 'Fonctionnalités Laboratoire',
    'labHome.features.subtitle': 'Tout ce dont vous avez besoin pour gérer efficacement votre laboratoire',
    'labHome.features.findClients.title': 'Trouver des Clients',
    'labHome.features.findClients.desc': 'Recherchez et connectez-vous avec des clients qui ont besoin de vos services de laboratoire.',
    'labHome.features.findClients.button': 'Rechercher des Clients',
    'labHome.features.managePAD.title': 'Gérer les Demandes PAD',
    'labHome.features.managePAD.desc': 'Recevez et gérez les demandes de collecte et d\'analyse de vos clients.',
    'labHome.features.managePAD.button': 'Voir les Demandes',
    'labHome.features.sendResults.title': 'Envoyer les Résultats',
    'labHome.features.sendResults.desc': 'Envoyez facilement les résultats d\'analyse à vos clients au format PDF.',
    'labHome.features.sendResults.button': 'Gérer les Résultats',
    'labHome.stats.clientsActive': 'Clients Actifs',
    'labHome.stats.analysesDone': 'Analyses Terminées',
    'labHome.stats.clientSatisfaction': 'Satisfaction Client',
    'labHome.stats.avgDelay': 'Délai Moyen',
    'labHome.howItWorks.title': 'Comment ça Marche',
    'labHome.howItWorks.subtitle': 'Processus simple en 3 étapes pour vous connecter avec vos clients',
    'labHome.howItWorks.step1.title': 'Rechercher des Clients',
    'labHome.howItWorks.step1.desc': 'Utilisez notre système de recherche pour trouver des clients qui ont besoin de vos services',
    'labHome.howItWorks.step2.title': 'Recevoir des Demandes',
    'labHome.howItWorks.step2.desc': 'Les clients vous envoient des demandes PAD que vous pouvez accepter ou refuser',
    'labHome.howItWorks.step3.title': 'Envoyer les Résultats',
    'labHome.howItWorks.step3.desc': 'Envoyez facilement les résultats d\'analyse dans un format PDF sécurisé',
    'labHome.cta.title': 'Prêt à commencer ?',
    'labHome.cta.subtitle': 'Rejoignez notre plateforme et commencez à vous connecter avec des clients dès aujourd\'hui',
    'labHome.cta.button': 'Aller au Tableau de Bord',

    // Footer
    'footer.subtitle': 'Laboratoires d\'Analyses Médicales',
    'footer.description': 'Réseau de laboratoires d\'analyses médicales offrant des services de qualité avec collecte à domicile, résultats rapides et suivi personnalisé.',
    'footer.services': 'Services',
    'footer.newsletter': 'Newsletter',
    'footer.stayUpdated': 'Restez informé de nos nouveaux services et conseils santé.',
    'footer.emailPlaceholder': 'Votre email',
    'footer.subscribing': 'Inscription...',
    'footer.subscribe': 'S\'abonner',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',

    // Notifications
    'notifications.loading': 'Chargement des notifications...',
    'notifications.empty': 'Aucune notification',
    'notifications.view': 'Voir',
    'notifications.viewAll': 'Voir toutes les notifications',
    'notifications.title': 'Notifications',
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.findLab': 'Find Laboratory',
    'nav.findClient': 'Find Client',
    'nav.results': 'My Results',
    'nav.login': 'Login',
    'nav.PADRequests': 'PAD Requests',
    'nav.logout': 'Logout',

    // Hero Section
    'hero.title': 'Medical Laboratory Analysis',
    'hero.subtitle': 'Find the nearest laboratory for your blood and urine tests.',
    'hero.findLab': 'Find Laboratory',
    'hero.login': 'Login',

    // Features
    'features.title': 'Why Choose Our Platform?',
    'features.subtitle': 'Discover the advantages of our medical laboratory network and enjoy quality service tailored to your needs.',
    'features.analyses.title': 'Complete Analysis',
    'features.analyses.desc': 'Blood, urine and biochemical tests with cutting-edge equipment and reliable results.',
    'features.results.title': 'Fast Results',
    'features.results.desc': 'Online access to your test results as quickly as possible, 24/7.',
    'features.home.title': 'Home Collection',
    'features.home.desc': 'Home collection service for your comfort and safety.',
    'features.security.title': 'Security & Privacy',
    'features.security.desc': 'Complete protection of your medical data with encryption and GDPR compliance.',
    'features.team.title': 'Professional Team',
    'features.team.desc': 'Qualified biologists and technicians for high-quality analysis.',
    'features.tracking.title': 'Personal Tracking',
    'features.tracking.desc': 'Complete history of your analyses and personalized advice from our experts.',

    // Find Laboratory
    'findLab.title': 'Find a Laboratory Near You',
    'findLab.subtitle': 'Quickly locate medical laboratories in your area and book appointments in just a few clicks.',
    'findLab.seoTitle': 'Find a Laboratory - Medical Testing',
    'findLab.seoDescription': 'Find the nearest medical laboratory to you. Location, opening hours and available services.',
    'findLab.keyword1': 'find laboratory',
    'findLab.keyword2': 'nearby laboratory',
    'findLab.keyword3': 'medical tests',
    'findLab.keyword4': 'laboratory location',
    'findLab.placeholder': 'Enter your address or postal code',
    'findLab.myLocation': 'My location',
    'findLab.search': 'Search',
    'findLab.call': 'Call',
    'findLab.homeCollection': 'Home collection',
    'findLab.services': 'Services:',
    'findLab.notFound': "Can't find a laboratory in your area?",
    'findLab.contact': 'Contact us for more information',
    'findLab.goLocation': 'Go location',
    'findLab.searching': 'Searching...',
    'findLab.loading': 'Loading laboratories...',
    'findLab.found': 'Laboratories found ({count})',
    'findLab.defaultName': 'Laboratory',
    'findLab.phoneNotAvailable': 'Phone not available',
    'findLab.mapCentered': 'Map centered',
    'findLab.mapCenteredDesc': 'Map centered on {labName}',
    'findLab.noResults': 'No laboratory found in this area.',

    // Map page strings
    'map.locationRequired': 'Location required',
    'map.needLocation': 'We need your position to show nearby laboratories',
    'map.nearbyLabs': 'Nearby Laboratories',
    'map.scrollHint': 'Scroll to view all laboratories',
    'map.openDays': 'Open days',
    'map.requestPAD': 'Request PAD',
    'map.locating': 'Locating...',
    'map.refreshPosition': 'Refresh Position',
    'map.goToMyPlace': 'My location',
    'map.positionUnknown': 'Unknown position',
    'map.enableLocation': 'Enable your location first.',
    'map.alreadySent': 'Already sent',
    'map.alreadySentDesc': 'You have already sent a request. Please wait for the response.',
    'map.accuracyApproximate': 'Approximate position',
    'map.accuracyVeryPrecise': 'Very precise position',
    'map.accuracyPrecise': 'Precise position',
    'map.accuracyGood': 'Good position',
    'map.accuracyIP': 'IP-based position',
    'map.interactiveMap': 'Interactive Map',
    'map.yourPosition': 'Your Position',
    'map.accuracy': 'Accuracy: ±{meters}m',
    'map.loadingLabs': 'Loading laboratories...',
    'map.noLabsInDB': 'No laboratory in database',
    'map.noLabsAvailable': 'No verified laboratory is available at the moment',
    'map.call': 'Call',
    'map.directions': 'Directions',
    'map.goToLocation': 'Go to location',
    'map.laboratories': 'laboratories',

    // PAD strings
    'PAD.loginRequired': 'You must be logged in to send a PAD request.',
    'PAD.sendError': 'Unable to send PAD request.',
    'PAD.sendSuccess': 'Request sent',
    'PAD.sendSuccessDesc': 'PAD request sent to {labName}',
    'PAD.defaultMessage': 'PAD request sent by client',
    'PAD.newRequest.title': 'New PAD request',
    'PAD.newRequest.message': 'has sent a PAD request.',
    'PAD.sentTitle': 'Request sent',
    'PAD.sentDesc': 'PAD request sent to',
    'PAD.acceptedTitle': 'PAD accepted',
    'PAD.acceptedMessage': 'The laboratory has accepted your request. Stay reachable, they may call you.',

    // Common
    'common.error': 'Error',
    'common.aClient': 'A client',
    'common.refresh': 'Refresh',

    // Hero (authenticated variants)
    'hero.auth.clientTitle': 'Find your laboratory',
    'hero.auth.labTitle': 'Manage your analyses',
    'hero.auth.clientSubtitle': 'Discover nearby laboratories and book appointments easily.',
    'hero.auth.labSubtitle': 'Access your analysis requests and manage your results.',

    // Authentication
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.loginTitle': 'Login',
    'auth.signupTitle': 'Create Account',
    'auth.loginSubtitle': 'Access your personal space',
    'auth.signupSubtitle': 'Join our laboratory platform',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.client': 'Client',
    'auth.laboratory': 'Laboratory',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone',
    'auth.birthDate': 'Date of Birth',
    'auth.labName': 'Laboratory Name',
    'auth.professionalEmail': 'Professional Email',
    'auth.siret': 'SIRET Number',
    'auth.address': 'Address',
    'auth.terms': 'I accept the terms of use',
    'auth.professionalTerms': 'I accept the professional terms',
    'auth.createAccount': 'Create account',

    // Services
    'services.bloodTests': 'Blood Tests',
    'services.bloodTests.desc': 'Complete blood and biochemistry tests',
    'services.urineTests': 'Urine Tests',
    'services.urineTests.desc': 'Complete urinary examinations',
    'services.homeCollection': 'Home Collection',
    'services.homeCollection.desc': 'Collection service at your home',
    'services.rapidResults': 'Rapid Results',
    'services.rapidResults.desc': 'Online access to your results',

    // Results
    'results.title': 'My Results',
    'results.download': 'Download',
    'results.status.completed': 'Completed',
    'results.status.pending': 'Pending',
    'results.status.reviewed': 'Reviewed',
    'results.labHistory': 'History of results sent to clients',
    'results.clientHistory': 'History of your medical test results',
    'results.searchPlaceholder': 'Search by title, description or name...',
    'results.results': 'Results',
    'results.loading': 'Loading...',
    'results.found': 'result(s) found',
    'results.loadingResults': 'Loading results',
    'results.loadError': 'Unable to load results.',
    'results.downloadStarted': 'Download started',
    'results.downloading': 'Downloading',
    'results.downloadErrorTitle': 'Download error',
    'results.downloadErrorDesc': 'Unable to download the file.',
    'results.newAvailableTitle': 'New result available',
    'results.newAvailableMessage': 'The laboratory has sent a result: "{filename}".',

    // Laboratory dashboard
    'lab.header': 'Laboratory Dashboard',
    'lab.headerSubtitle': 'Manage your requests, results and laboratory settings',
    'lab.findClient': 'Find Client',
    'lab.PADRequests': 'PAD Requests',
    'lab.searchClients': 'Search Clients',
    'lab.searchClientsDesc': 'Find clients and send them PAD requests',
    'lab.searchPlaceholder': 'Search by name, email or phone...',
    'lab.sendResult': 'Send Result',
    'lab.noClientFor': 'No client found',
    'lab.noClientsYet': 'No clients registered yet',
    'lab.noClientsHint': 'Clients will appear here once they register on the platform',
    'lab.receivedPAD': 'Received PAD Requests',
    'lab.receivedPADDesc': 'Manage PAD requests sent by clients',
    'lab.status.pending': 'Pending',
    'lab.status.accepted': 'Accepted',
    'lab.status.rejected': 'Rejected',
    'lab.viewExactLocation': 'View Exact Location',
    'lab.accept': 'Accept',
    'lab.reject': 'Reject',

    // Laboratory Home Page
    'labHome.seoTitle': 'Laboratory Space - SihaaExpress',
    'labHome.seoDescription': 'Complete platform for medical analysis laboratories. Connect with clients, manage requests, and optimize your workflow.',
    'labHome.keyword1': 'laboratory',
    'labHome.keyword2': 'medical analyses',
    'labHome.keyword3': 'PAD',
    'labHome.keyword4': 'results',
    'labHome.title': 'Laboratory Space',
    'labHome.heroDescription': 'Complete platform for medical analysis laboratories. Connect with clients, manage requests, and optimize your workflow.',
    'labHome.ctaFindClients': 'Find Clients',
    'labHome.ctaManageRequests': 'Manage Requests',
    'labHome.features.title': 'Laboratory Features',
    'labHome.features.subtitle': 'Everything you need to efficiently manage your laboratory',
    'labHome.features.findClients.title': 'Find Clients',
    'labHome.features.findClients.desc': 'Search and connect with clients who need your laboratory services.',
    'labHome.features.findClients.button': 'Search Clients',
    'labHome.features.managePAD.title': 'Manage PAD Requests',
    'labHome.features.managePAD.desc': 'Receive and manage collection and analysis requests from your clients.',
    'labHome.features.managePAD.button': 'View Requests',
    'labHome.features.sendResults.title': 'Send Results',
    'labHome.features.sendResults.desc': 'Easily send analysis results to your clients in PDF format.',
    'labHome.features.sendResults.button': 'Manage Results',
    'labHome.stats.clientsActive': 'Active Clients',
    'labHome.stats.analysesDone': 'Analyses Completed',
    'labHome.stats.clientSatisfaction': 'Client Satisfaction',
    'labHome.stats.avgDelay': 'Average Delay',
    'labHome.howItWorks.title': 'How it Works',
    'labHome.howItWorks.subtitle': 'Simple 3-step process to connect with your clients',
    'labHome.howItWorks.step1.title': 'Search Clients',
    'labHome.howItWorks.step1.desc': 'Use our search system to find clients who need your services',
    'labHome.howItWorks.step2.title': 'Receive Requests',
    'labHome.howItWorks.step2.desc': 'Clients send you PAD requests that you can accept or refuse',
    'labHome.howItWorks.step3.title': 'Send Results',
    'labHome.howItWorks.step3.desc': 'Easily send analysis results in a secure PDF format',
    'labHome.cta.title': 'Ready to start?',
    'labHome.cta.subtitle': 'Join our platform and start connecting with clients today',
    'labHome.cta.button': 'Go to Dashboard',

    // Footer
    'footer.subtitle': 'Medical Analysis Laboratories',
    'footer.description': 'Network of medical analysis laboratories offering quality services with home collection, fast results and personalized follow-up.',
    'footer.services': 'Services',
    'footer.newsletter': 'Newsletter',
    'footer.stayUpdated': 'Stay informed about our new services and health tips.',
    'footer.emailPlaceholder': 'Your email',
    'footer.subscribing': 'Subscribing...',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',

    // Notifications
    'notifications.loading': 'Loading notifications...',
    'notifications.empty': 'No notifications',
    'notifications.view': 'View',
    'notifications.viewAll': 'View all notifications',
    'notifications.title': 'Notifications',
  },

  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'حول',
    'nav.services': 'الخدمات',
    'nav.findLab': 'العثور على مختبر',
    'nav.findClient': 'البحث عن عميل',
    'nav.results': 'نتائجي',
    'nav.login': 'تسجيل الدخول',
    'nav.PADRequests': 'طلبات PAD',
    'nav.logout': 'تسجيل الخروج',

    // Hero Section
    'hero.title': 'تحليل المختبرات الطبية',
    'hero.subtitle': 'اعثر على أقرب مختبر لتحاليل الدم والبول.',
    'hero.findLab': 'العثور على مختبر',
    'hero.login': 'تسجيل الدخول',

    // Features
    'features.title': 'لماذا تختار منصتنا؟',
    'features.subtitle': 'اكتشف مزايا شبكة المختبرات الطبية لدينا واستمتع بخدمة عالية الجودة مصممة لتلبية احتياجاتك.',
    'features.analyses.title': 'تحليل شامل',
    'features.analyses.desc': 'تحاليل الدم والبول والكيمياء الحيوية بأحدث المعدات ونتائج موثوقة.',
    'features.results.title': 'نتائج سريعة',
    'features.results.desc': 'الوصول عبر الإنترنت إلى نتائج التحاليل في أسرع وقت ممكن، على مدار الساعة.',
    'features.home.title': 'جمع منزلي',
    'features.home.desc': 'خدمة الجمع المنزلي لراحتك وأمانك.',
    'features.security.title': 'الأمان والخصوصية',
    'features.security.desc': 'حماية كاملة لبياناتك الطبية مع التشفير والامتثال لقانون حماية البيانات.',
    'features.team.title': 'فريق محترف',
    'features.team.desc': 'علماء أحياء وفنيون مؤهلون لتحليل عالي الجودة.',
    'features.tracking.title': 'متابعة شخصية',
    'features.tracking.desc': 'تاريخ كامل لتحاليلك ونصائح شخصية من خبرائنا.',

    // Find Laboratory
    'findLab.title': 'اعثر على مختبر بالقرب منك',
    'findLab.subtitle': 'حدد موقع المختبرات الطبية في منطقتك بسرعة واحجز المواعيد بنقرات قليلة.',
    'findLab.seoTitle': 'ابحث عن مختبر - تحاليل طبية',
    'findLab.seoDescription': 'اعثر على أقرب مختبر طبي إليك. الموقع، أوقات العمل والخدمات المتاحة.',
    'findLab.keyword1': 'ابحث عن مختبر',
    'findLab.keyword2': 'مختبر قريب',
    'findLab.keyword3': 'تحاليل طبية',
    'findLab.keyword4': 'موقع المختبر',
    'findLab.placeholder': 'أدخل عنوانك أو الرمز البريدي',
    'findLab.myLocation': 'موقعي',
    'findLab.search': 'بحث',
    'findLab.call': 'اتصال',
    'findLab.homeCollection': 'جمع منزلي',
    'findLab.services': 'الخدمات:',
    'findLab.notFound': 'لا يمكنك العثور على مختبر في منطقتك؟',
    'findLab.contact': 'اتصل بنا للحصول على مزيد من المعلومات',
    'findLab.goLocation': 'اذهب إلى الموقع',
    'findLab.searching': 'جاري البحث...',
    'findLab.loading': 'تحميل المختبرات...',
    'findLab.found': 'المختبرات الموجودة ({count})',
    'findLab.defaultName': 'مختبر',
    'findLab.phoneNotAvailable': 'الهاتف غير متوفر',
    'findLab.mapCentered': 'تم توسيط الخريطة',
    'findLab.mapCenteredDesc': 'تم توسيط الخريطة على {labName}',
    'findLab.noResults': 'لم يتم العثور على مختبر في هذه المنطقة.',

    // Map page strings
    'map.locationRequired': 'مطلوب تحديد الموقع',
    'map.needLocation': 'نحتاج إلى موقعك لعرض المختبرات القريبة',
    'map.nearbyLabs': 'مختبرات قريبة',
    'map.scrollHint': 'مرر لعرض جميع المختبرات',
    'map.openDays': 'أيام العمل',
    'map.requestPAD': 'طلب PAD',
    'map.locating': 'جاري تحديد الموقع...',
    'map.refreshPosition': 'تحديث الموقع',
    'map.goToMyPlace': 'موقعي',
    'map.positionUnknown': 'موقع غير معروف',
    'map.enableLocation': 'قم بتفعيل تحديد الموقع أولاً.',
    'map.alreadySent': 'تم الإرسال بالفعل',
    'map.alreadySentDesc': 'لقد أرسلت طلباً بالفعل. يرجى انتظار الرد.',
    'map.accuracyApproximate': 'موقع تقريبي',
    'map.accuracyVeryPrecise': 'موقع دقيق جداً',
    'map.accuracyPrecise': 'موقع دقيق',
    'map.accuracyGood': 'موقع جيد',
    'map.accuracyIP': 'موقع مبني على IP',
    'map.interactiveMap': 'خريطة تفاعلية',
    'map.yourPosition': 'موقعك',
    'map.accuracy': 'الدقة: ±{meters}م',
    'map.loadingLabs': 'تحميل المختبرات...',
    'map.noLabsInDB': 'لا يوجد مختبر في قاعدة البيانات',
    'map.noLabsAvailable': 'لا يوجد مختبر معتمد متاح في الوقت الحالي',
    'map.call': 'اتصال',
    'map.directions': 'الاتجاهات',
    'map.goToLocation': 'الذهاب إلى الموقع',
    'map.laboratories': 'مختبرات',

    // PAD strings
    'PAD.loginRequired': 'يجب أن تكون مسجل الدخول لإرسال طلب PAD.',
    'PAD.sendError': 'غير قادر على إرسال طلب PAD.',
    'PAD.sendSuccess': 'تم إرسال الطلب',
    'PAD.sendSuccessDesc': 'تم إرسال طلب PAD إلى {labName}',
    'PAD.defaultMessage': 'طلب PAD مرسل من العميل',
    'PAD.newRequest.title': 'طلب PAD جديد',
    'PAD.newRequest.message': 'أرسل طلب PAD.',
    'PAD.sentTitle': 'تم الإرسال',
    'PAD.sentDesc': 'تم إرسال طلب PAD إلى',
    'PAD.acceptedTitle': 'تم قبول PAD',
    'PAD.acceptedMessage': 'قبل المختبر طلبك. ابق متاحاً، قد يتصلون بك.',

    // Common
    'common.error': 'خطأ',
    'common.aClient': 'عميل',
    'common.refresh': 'تحديث',

    // Hero (authenticated variants)
    'hero.auth.clientTitle': 'اعثر على مختبرك',
    'hero.auth.labTitle': 'إدارة التحاليل',
    'hero.auth.clientSubtitle': 'اكتشف المختبرات القريبة واحجز المواعيد بسهولة.',
    'hero.auth.labSubtitle': 'الوصول إلى طلبات التحاليل وإدارة النتائج.',

    // Authentication
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.loginTitle': 'تسجيل الدخول',
    'auth.signupTitle': 'إنشاء حساب',
    'auth.loginSubtitle': 'الوصول إلى مساحتك الشخصية',
    'auth.signupSubtitle': 'انضم إلى منصة المختبرات لدينا',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.client': 'عميل',
    'auth.laboratory': 'مختبر',
    'auth.firstName': 'الاسم الأول',
    'auth.lastName': 'اسم العائلة',
    'auth.phone': 'الهاتف',
    'auth.birthDate': 'تاريخ الميلاد',
    'auth.labName': 'اسم المختبر',
    'auth.professionalEmail': 'البريد الإلكتروني المهني',
    'auth.siret': 'رقم SIRET',
    'auth.address': 'العنوان',
    'auth.terms': 'أوافق على شروط الاستخدام',
    'auth.professionalTerms': 'أوافق على الشروط المهنية',
    'auth.createAccount': 'إنشاء حساب',

    // Services
    'services.bloodTests': 'تحاليل الدم',
    'services.bloodTests.desc': 'تحاليل الدم والكيمياء الحيوية الكاملة',
    'services.urineTests': 'تحاليل البول',
    'services.urineTests.desc': 'فحوصات البول الكاملة',
    'services.homeCollection': 'الجمع المنزلي',
    'services.homeCollection.desc': 'خدمة الجمع في منزلك',
    'services.rapidResults': 'نتائج سريعة',
    'services.rapidResults.desc': 'الوصول عبر الإنترنت إلى نتائجك',

    // Results
    'results.title': 'نتائجي',
    'results.download': 'تحميل',
    'results.status.completed': 'مكتمل',
    'results.status.pending': 'قيد الانتظار',
    'results.status.reviewed': 'تمت المراجعة',
    'results.labHistory': 'سجل النتائج المرسلة إلى العملاء',
    'results.clientHistory': 'سجل نتائج تحاليلك الطبية',
    'results.searchPlaceholder': 'ابحث حسب العنوان أو الوصف أو الاسم...',
    'results.results': 'النتائج',
    'results.loading': 'جاري التحميل...',
    'results.found': 'نتيجة(نتائج) تم العثور عليها',
    'results.loadingResults': 'جاري تحميل النتائج',
    'results.loadError': 'تعذر تحميل النتائج.',
    'results.downloadStarted': 'بدأ التنزيل',
    'results.downloading': 'جارٍ تنزيل',
    'results.downloadErrorTitle': 'خطأ في التنزيل',
    'results.downloadErrorDesc': 'تعذر تنزيل الملف.',
    'results.newAvailableTitle': 'نتيجة جديدة متاحة',
    'results.newAvailableMessage': 'أرسل المختبر نتيجة: "{filename}".',

    // Laboratory dashboard
    'lab.header': 'لوحة تحكم المختبر',
    'lab.headerSubtitle': 'إدارة الطلبات والنتائج وإعدادات المختبر',
    'lab.findClient': 'البحث عن عميل',
    'lab.PADRequests': 'طلبات PAD',
    'lab.searchClients': 'البحث عن العملاء',
    'lab.searchClientsDesc': 'ابحث عن العملاء وأرسل لهم طلبات PAD',
    'lab.searchPlaceholder': 'ابحث بالاسم أو البريد أو الهاتف...',
    'lab.sendResult': 'إرسال النتيجة',
    'lab.noClientFor': 'لا يوجد عميل',
    'lab.noClientsYet': 'لا يوجد عملاء حتى الآن',
    'lab.noClientsHint': 'سيظهر العملاء هنا بعد التسجيل في المنصة',
    'lab.receivedPAD': 'طلبات PAD المستلمة',
    'lab.receivedPADDesc': 'إدارة طلبات PAD المرسلة من العملاء',
    'lab.status.pending': 'قيد الانتظار',
    'lab.status.accepted': 'مقبولة',
    'lab.status.rejected': 'مرفوضة',
    'lab.viewExactLocation': 'عرض الموقع الدقيق',
    'lab.accept': 'قبول',
    'lab.reject': 'رفض',

    // Laboratory Home Page
    'labHome.seoTitle': 'مساحة المختبر - SihaaExpress',
    'labHome.seoDescription': 'منصة متكاملة لمختبرات التحاليل الطبية. تواصل مع العملاء، وأدر الطلبات، وحسّن سير العمل.',
    'labHome.keyword1': 'مختبر',
    'labHome.keyword2': 'تحاليل طبية',
    'labHome.keyword3': 'PAD',
    'labHome.keyword4': 'نتائج',
    'labHome.title': 'مساحة المختبر',
    'labHome.heroDescription': 'منصة متكاملة لمختبرات التحاليل الطبية. تواصل مع العملاء، وأدر الطلبات، وحسّن سير العمل.',
    'labHome.ctaFindClients': 'البحث عن عملاء',
    'labHome.ctaManageRequests': 'إدارة الطلبات',
    'labHome.features.title': 'ميزات المختبر',
    'labHome.features.subtitle': 'كل ما تحتاجه لإدارة مختبرك بكفاءة',
    'labHome.features.findClients.title': 'البحث عن عملاء',
    'labHome.features.findClients.desc': 'ابحث وتواصل مع العملاء الذين يحتاجون إلى خدمات مختبرك.',
    'labHome.features.findClients.button': 'ابحث عن العملاء',
    'labHome.features.managePAD.title': 'إدارة طلبات PAD',
    'labHome.features.managePAD.desc': 'استقبال وإدارة طلبات السحب والتحاليل من عملائك.',
    'labHome.features.managePAD.button': 'عرض الطلبات',
    'labHome.features.sendResults.title': 'إرسال النتائج',
    'labHome.features.sendResults.desc': 'أرسل نتائج التحاليل بسهولة إلى عملائك بصيغة PDF.',
    'labHome.features.sendResults.button': 'إدارة النتائج',
    'labHome.stats.clientsActive': 'عملاء نشطون',
    'labHome.stats.analysesDone': 'تحاليل منجزة',
    'labHome.stats.clientSatisfaction': 'رضا العملاء',
    'labHome.stats.avgDelay': 'متوسط المدة',
    'labHome.howItWorks.title': 'كيف تعمل المنصة',
    'labHome.howItWorks.subtitle': 'عملية بسيطة من 3 خطوات للتواصل مع عملائك',
    'labHome.howItWorks.step1.title': 'ابحث عن العملاء',
    'labHome.howItWorks.step1.desc': 'استخدم نظام البحث لدينا للعثور على العملاء الذين يحتاجون إلى خدماتك',
    'labHome.howItWorks.step2.title': 'استقبال الطلبات',
    'labHome.howItWorks.step2.desc': 'يرسل العملاء طلبات PAD يمكنك قبولها أو رفضها',
    'labHome.howItWorks.step3.title': 'أرسل النتائج',
    'labHome.howItWorks.step3.desc': 'أرسل نتائج التحاليل بسهولة بصيغة PDF آمنة',
    'labHome.cta.title': 'جاهز للبدء؟',
    'labHome.cta.subtitle': 'انضم إلى منصتنا وابدأ بالتواصل مع العملاء اليوم',
    'labHome.cta.button': 'الانتقال إلى لوحة التحكم',

    // Footer
    'footer.subtitle': 'مختبرات التحاليل الطبية',
    'footer.description': 'شبكة من مختبرات التحاليل الطبية تقدم خدمات عالية الجودة مع جمع منزلي ونتائج سريعة ومتابعة شخصية.',
    'footer.services': 'الخدمات',
    'footer.newsletter': 'النشرة الإخبارية',
    'footer.stayUpdated': 'ابقَ على اطلاع على خدماتنا الجديدة ونصائح الصحة.',
    'footer.emailPlaceholder': 'بريدك الإلكتروني',
    'footer.subscribing': 'جارٍ الاشتراك...',
    'footer.subscribe': 'اشترك',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الاستخدام',

    // Notifications
    'notifications.loading': 'جاري تحميل الإشعارات...',
    'notifications.empty': 'لا توجد إشعارات',
    'notifications.view': 'عرض',
    'notifications.viewAll': 'عرض كل الإشعارات',
    'notifications.title': 'الإشعارات',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr'); // French as default

  const t = (key: string, params?: Record<string, any>) => {
    const translation = translations[language][key] || key;

    if (params) {
      return Object.keys(params).reduce((str, param) => {
        return str.replace(new RegExp(`{${param}}`, 'g'), params[param]);
      }, translation);
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
